### ISSUE TITLE
Import of github_membership won't work - Terraform crashes

### ISSUE THREAD

**Issue by Nowaker** [terraform-providers/terraform-provider-github#49]
Terraform version: Terraform v0.10.6
Plugin version: 0.1.1

`terraform import github_membership.org_membership_Nowaker Nowaker`

Most relevant error:
```
import github_membership.org_membership_Nowaker result: Nowaker: github_membership.org_membership_Nowaker: unexpected EOF
panic: runtime error: index out of range
```

Full output:
```
nowaker@nwkr-desktop ..old/devops/team-resources/company-wide (git)-[feature/terraform-for-github] % terraform import github_membership.org_membership_Nowaker Nowaker
github_membership.org_membership_Nowaker: Importing from ID "Nowaker"...
github_membership.org_membership_Nowaker: Import complete!
  Imported github_membership (ID: Nowaker)
github_membership.org_membership_Nowaker: Refreshing state... (ID: Nowaker)
Error importing: 1 error(s) occurred:

* github_membership.org_membership_Nowaker (import id: Nowaker): 1 error(s) occurred:

* import github_membership.org_membership_Nowaker result: Nowaker: github_membership.org_membership_Nowaker: unexpected EOF
panic: runtime error: index out of range
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: 
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: goroutine 34 [running]:
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: github.com/terraform-providers/terraform-provider-github/github.parseTwoPartID(0xc42028a524, 0x7, 0x0, 0x0, 0xc420282958, 0x9b7338)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-github/github/util.go:46 +0x9e
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: github.com/terraform-providers/terraform-provider-github/github.resourceGithubMembershipRead(0xc4202943f0, 0xa323a0, 0xc420270a20, 0x0, 0xf89b20)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-github/github/resource_github_membership.go:55 +0x81
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42001aea0, 0xc420298370, 0xa323a0, 0xc420270a20, 0xc420202bf8, 0xc42027a901, 0x0)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420058a10, 0xc420298320, 0xc420298370, 0x7f86cf5dd2c0, 0x0, 0x0)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4200d9f40, 0xc42028a370, 0xc42028a5b0, 0x0, 0x0)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-github/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: reflect.Value.call(0xc42011f560, 0xc4201161c8, 0x13, 0xb6b3a3, 0x4, 0xc420282f20, 0x3, 0x3, 0x437f0c, 0xc420035738, ...)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /usr/local/go/src/reflect/value.go:434 +0x91f
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: reflect.Value.Call(0xc42011f560, 0xc4201161c8, 0x13, 0xc420035720, 0x3, 0x3, 0x0, 0x180000, 0x0)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /usr/local/go/src/reflect/value.go:302 +0xa4
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: net/rpc.(*service).call(0xc420111a80, 0xc420111a40, 0xc42010de40, 0xc420119900, 0xc420270460, 0xa353e0, 0xc42028a370, 0x16, 0xa35420, 0xc42028a5b0, ...)
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /usr/local/go/src/net/rpc/server.go:387 +0x144
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4: created by net/rpc.(*Server).ServeCodec
2017-09-26T13:04:52.448-0500 [DEBUG] plugin.terraform-provider-github_v0.1.1_x4:        /usr/local/go/src/net/rpc/server.go:481 +0x404
2017/09/26 13:04:52 [ERROR] root: eval: *terraform.EvalRefresh, err: github_membership.org_membership_Nowaker: unexpected EOF
2017/09/26 13:04:52 [ERROR] root: eval: *terraform.EvalSequence, err: github_membership.org_membership_Nowaker: unexpected EOF
2017/09/26 13:04:52 [TRACE] [walkImport] Exiting eval tree: import github_membership.org_membership_Nowaker result: Nowaker
2017-09-26T13:04:52.448-0500 [DEBUG] plugin: plugin process exited: path=/home/nowaker/projekty/tenfold/devops/team-resources/company-wide/.terraform/plugins/linux_amd64/terraform-provider-github_v0.1.1_x4
2017/09/26 13:04:52 [TRACE] dag/walk: upstream errored, not walking "provider.github (close)"
2017/09/26 13:04:52 [TRACE] dag/walk: upstream errored, not walking "root"
2017/09/26 13:04:52 [DEBUG] plugin: waiting for all plugin processes to complete...
2017-09-26T13:04:52.449-0500 [WARN ] plugin: error closing client during Kill: err="connection is shut down"
2017-09-26T13:04:52.449-0500 [DEBUG] plugin: plugin process exited: path=/home/nowaker/projekty/tenfold/devops/team-resources/company-wide/.terraform/plugins/linux_amd64/terraform-provider-external_v1.0.0_x4



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by radeksimko** [comment]
Hi @Nowaker 
thanks for the report and sorry for the delay. I have a fix of the crash pending review in #108 

Please keep in mind that we expect colon-separated format of the ID when importing resources, [as documented](https://www.terraform.io/docs/providers/github/r/membership.html#import). Terraform will return appropriate error message reminding user the expected format after we ship the bugfix.
